XCTest simulator version of build_and_inject
shinydevelopment/SimulatorStatusMagic pull request #122
Opened 2023-11-27 08:57 UTC by nflore

I was automating screenshots with XCTest and the normal version of the build_and_inject script didn't find the Clone simulator(s) that opens.

--set testing will show the simulators used there, added a separate file for it.

2023-11-28 01:15 UTC, chrisvasselli requested changes
Thanks so much for this update, this is great.

I actually use parallel testing, but took a different approach to solve this problem. I create a simulator, then run build_and_inject.sh on that simulator, then run my tests on that simulator using `xcodebuild -parallel-testing-enabled YES`. That way, the simulator is duplicated with the correct status bar already setup, and I have found that it maintains that across the duplication.

I'm not sure which approach is better, but in a way I wonder if that's simpler than needing to inject into each duplicated simulator individual? What do you think?

2023-11-28 01:15 UTC, chrisvasselli commented on build_and_inject_test.sh
Maybe instead of a separate script this could be a flag that is passed to `build_and_inject.sh`, so we don't have to maintain two largely duplicate scripts?

2023-11-28 01:15 UTC, chrisvasselli commented on README.md
> +**For XCTest simulators, use `build_and_inject_test.sh booted`** - Replace "booted" with a simulator UDID to target a specific simulator. Retrieve them with `xcrun simctl --set testing list devices |
Nice, I think this is a great addition.

We should also clarify that this is only for duplicated simulators created by using the `-parallel-testing-enabled` flag on xcodebuild. If you are using XCTest but not using parallel testing, this line might be misleading.

2025-03-27 02:54 UTC, JPWhiteza approved these changes

2025-03-27 02:56 UTC, JPWhiteza approved these changes

2025-03-27 03:01 UTC, JPWhiteza approved these changes

2025-03-27 03:01 UTC, JPWhiteza commented on README.md
> -**tl;dr** Running `build_and_inject.sh booted` will apply a default status bar to the running simulator. Replace "booted" with a simulator UDID to target a specific simulator.
###

2025-03-27 03:20 UTC, JPWhiteza approved these changes

2025-03-27 10:06 UTC, JPWhiteza approved these changes
The request had been changed

2025-06-16 20:02 UTC, closed without merging